#!/usr/bin/env bash

set -e

BASEPATH="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
BASEDIR="$(dirname "${BASEPATH}")"
CLUSTER_NAME="minimal-cluster"

check_dependency() {
  if ! command -v $1 >/dev/null; then
    echo "$1 is required to run this script, please install it."
    exit 1
  fi
}

check_dependency k3d

if k3d cluster ls "$CLUSTER_NAME" >/dev/null; then
  read -p "$CLUSTER_NAME already exists, do you want to recreate it? (y/n) " recreate
  if [[ "$recreate" =~ ^[Yy]$ ]]; then
    echo "Deleting cluster..."
    k3d cluster delete "$CLUSTER_NAME"
  else
    echo "Exiting..."
    exit 0
  fi
fi

if ! k3d cluster ls | grep $CLUSTER_NAME; then
  echo "Creating cluster..."
  k3d cluster create -c ${BASEDIR}/kubernetes/k3d-config-minimal.yaml "$CLUSTER_NAME"
  echo "Setting up the context..."
  kubectl config use-context k3d-${CLUSTER_NAME}
fi
